### ISSUE TITLE
Unlucky Dogs 

### ISSUE THREAD

**Issue by Aladore384** [unknown321/mgswaifus#5]
Doom Squirrel, Cunning Mongoose, and Dancing Mongoose are prisoners from Unlucky Dogs sideops, just like Dire Armadillo. Still have to figure out who Blue Armadillo is though.

EDIT: Now that I think of it, Blue Armadillo is most likely a dummied Ground Zeroes soldier. His ID and language fit the profile.

**Comment by unknown321** [comment]
do you have exact mission->soldier mapping? I'd like to have as much info as possible since two soldiers already have their mission numbers.

**Comment by Aladore384** [comment]
Dire Armadillo - Unlucky Dog #62, note sure why he's marked as Commander on your sheet, but he's a mere prisoner
Doom Squirrel - Unlucky Dog #63, prisoner
Cunning Mongoose - Unlucky Dog #64, prisoner
Dancing Mongoose  - Unlucky Dog #65, prisoner

**Comment by unknown321** [comment]
Dire Armadillo was marked as a commander in game files. Updated all unlucky dogs.
