### ISSUE TITLE
Blue Armadillo

### ISSUE THREAD

**Issue by Aladore384** [unknown321/mgswaifus#6]
hello, it's been a few years. TIL that at a certain shop pre-ordering GZ would have given you a secret recruit.

maybe that's who Blue Armadillo is?

> Japanese pre-order Secret Recruit DLC for The Phantom Pain. Exclusive to GAMETUTAYA.

Source: https://metalgear.fandom.com/wiki/Metal_Gear_Solid_V:_Ground_Zeroes#Downloadable_content_for_The_Phantom_Pain

**Comment by unknown321** [comment]
It's skulls: https://metalgear.fandom.com/wiki/Mother_Base_Bonus_Staff

**Comment by Aladore384** [comment]
ah damn! here i thought the mystery was finally solved. well guess he was just dummied out then.
